import time
import subprocess

subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
