# Copyright © 2021 by University of Luxembourg.
# Developed at SnT APSIA by:
# Aditya Damodaran, aditya.damodaran@uni.lu
# Alfredo Rial, alfredo.rial@uni.lu

import time
import subprocess

subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(20)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
subprocess.call(["python2.7", "vectorcommitment.py"])
time.sleep(10)
